export const baseURL = 'http://localhost:3000/api/v2'
export const REDIRECT_URI = 'https://ya-praktikum.tech/api/v2'
export const resourceURL = 'http://localhost:3000/api/v2/resources'
export const dateLocale = 'ru-RU'
export const oauthRedirectURI = 'http://localhost:3000'
