export const emodjisList = [
  '\u{1F600}', // name: 'grinning face', emoji: '😀'
  '\u{1F609}', //name: 'winking face', emoji: '😉' },
  '\u{1F602}', //name: 'face with tears of joy', emoji: '😂' },
  '\u{1F60A}', //name: 'smiling face with smiling eyes', emoji: '😊' },
  '\u{1F923}', //name: 'Rolling On The Floor Laughing', emoji: '🤣' },
  '\u{1F642}', //name: 'slightly smiling face', emoji: '🙂' },
  '\u{1F60D}', //name: 'smiling face with heart-eyes', emoji: '😍' },
  '\u{1F914}', //name: 'Thinking face', emoji: '🤔' },
  '\u{1F9D0}', //name: 'Face With Monocle', emoji: '🧐' },
  '\u{1F92C}', //name: 'Serious Face With Symbols Covering Mouth',emoji: '🤬',
  '\u{1F621}', //name: 'Pouting Face', emoji: '😡' },
  '\u{1F624}', //name: 'Face with Look of Triumph', emoji: '😤' },
  '\u{1F4A9}', //name: 'Pile of Poo', emoji: '💩' },
  '\u{1F47B}', //name: 'Ghost', emoji: '👻' },
  '\u{1F921}', //name: 'Clown Face', emoji: '🤡' },
  '\u{1F649}', //name: 'Hear-No-Evil Monkey', emoji: '🙉' },
  '\u{1F64A}', //name: 'Speak-No-Evil Monkey', emoji: '🙊' },
  '\u{1F648}', //name: 'See-No-Evil Monkey', emoji: '🙈' },
  '\u{2764}', //name: 'red heart', emoji: '❤️' }, //из двух символов Юникода: «❤» (U+2764) и модифицирующего U+FE0F
  '\u{1F590}', //name: 'Raised Hand with Fingers Splayed', emoji: '🖐' },
  '\u{1F64F}', //name: 'Person with Folded Hands', emoji: '🙏' },
  '\u{1F91D}', //name: 'Handshake', emoji: '🤝' },
  '\u{1F44C}', //name: 'Ok Hand Sign', emoji: '👌' },
  '\u{1F91F}', //name: 'I Love You Hand Sign', emoji: '🤟' },
  '\u{270C}', //name: 'victory hand', emoji: '✌️' },
  '\u{1F90C}', //name: 'Pinched Fingers', emoji: '🤌' },
  '\u{1F446}', //name: 'White Up Pointing Backhand Index', emoji: '👆' },
  '\u{1F447}', // 'white down pointing backhand index', emoji: '👇',
  '\u{1F44D}', // name: 'Thumbs Up Sign', emoji: '👍' },
  '\u{1F937}', // name: 'shrug', emoji: '🤷' },
  '\u{1F926}', // name: 'face palm', emoji: '🤦' },
  '\u{1F483}', // name: 'dancer', emoji: '💃' },
  '\u{1F339}', // name: 'rose', emoji: '🌹' },
  '\u{1F338}', // name: 'cherry blossom', emoji: '🌸' },
  '\u{1F942}', // name: 'clinking glasses', emoji: '🥂' },
  '\u{1F37B}', // name: 'clinking beer mugs', emoji: '🍻' },
  '\u{2615}', //name: 'hot beverage', emoji: '☕' },
  '\u{1F389}', // name: 'party popper', emoji: '🎉' },
  '\u{26BD}', //name: 'soccer ball', emoji: '⚽' },
  '\u{1F3D6}', // name: 'beach with umbrella', emoji: '🏖' },
]

// export const emodjisList = [
//   { unicode: '\u1F600', name: 'grinning face', emoji: '😀' },
//   { unicode: '\u1F609', name: 'winking face', emoji: '😉' },
//   { unicode: 'U+1F602', name: 'face with tears of joy', emoji: '😂' },
//   { unicode: 'U+1F60A', name: 'smiling face with smiling eyes', emoji: '😊' },
//   { unicode: 'U+1F923', name: 'Rolling On The Floor Laughing', emoji: '🤣' },
//   { unicode: 'U+1F642', name: 'slightly smiling face', emoji: '🙂' },
//   { unicode: 'U+1F60D', name: 'smiling face with heart-eyes', emoji: '😍' },
//   { unicode: 'U+1F914', name: 'Thinking face', emoji: '🤔' },
//   { unicode: 'U+1F9D0', name: 'Face With Monocle', emoji: '🧐' },
//   {
//     unicode: 'U+1F92C',
//     name: 'Serious Face With Symbols Covering Mouth',
//     emoji: '🤬',
//   },
//   { unicode: 'U+1F621', name: 'Pouting Face', emoji: '😡' },
//   { unicode: 'U+1F624', name: 'Face with Look of Triumph', emoji: '😤' },
//   { unicode: 'U+1F4A9', name: 'Pile of Poo', emoji: '💩' },
//   { unicode: 'U+1F47B', name: 'Ghost', emoji: '👻' },
//   { unicode: 'U+1F921', name: 'Clown Face', emoji: '🤡' },
//   { unicode: 'U+1F649', name: 'Hear-No-Evil Monkey', emoji: '🙉' },
//   { unicode: 'U+1F64A', name: 'Speak-No-Evil Monkey', emoji: '🙊' },
//   { unicode: 'U+1F648', name: 'See-No-Evil Monkey', emoji: '🙈' },
//   { unicode: 'U+2764', name: 'red heart', emoji: '❤️' },
//   { unicode: 'U+1F590', name: 'Raised Hand with Fingers Splayed', emoji: '🖐' },
//   { unicode: 'U+1F64F', name: 'Person with Folded Hands', emoji: '🙏' },
//   { unicode: 'U+1F91D', name: 'Handshake', emoji: '🤝' },
//   { unicode: 'U+1F44C', name: 'Ok Hand Sign', emoji: '👌' },
//   { unicode: 'U+1F91F', name: 'I Love You Hand Sign', emoji: '🤟' },
//   { unicode: 'U+270C', name: 'victory hand', emoji: '✌️' },
//   { unicode: 'U+1F90C', name: 'Pinched Fingers', emoji: '🤌' },
//   { unicode: 'U+1F446', name: 'White Up Pointing Backhand Index', emoji: '👆' },
//   {
//     unicode: 'U+1F447',
//     name: 'white down pointing backhand index',
//     emoji: '👇',
//   },
//   { unicode: 'U+1F44D', name: 'Thumbs Up Sign', emoji: '👍' },
//   { unicode: 'U+1F937', name: 'shrug', emoji: '🤷' },
//   { unicode: 'U+1F926', name: 'face palm', emoji: '🤦' },
//   { unicode: 'U+1F483', name: 'dancer', emoji: '💃' },
//   { unicode: 'U+1F339', name: 'rose', emoji: '🌹' },
//   { unicode: 'U+1F338', name: 'cherry blossom', emoji: '🌸' },
//   { unicode: 'U+1F942', name: 'clinking glasses', emoji: '🥂' },
//   { unicode: 'U+1F37B', name: 'clinking beer mugs', emoji: '🍻' },
//   { unicode: 'U+2615', name: 'hot beverage', emoji: '☕' },
//   { unicode: 'U+1F389', name: 'party popper', emoji: '🎉' },
//   { unicode: 'U+26BD', name: 'soccer ball', emoji: '⚽' },
//   { unicode: 'U+1F3D6', name: 'beach with umbrella', emoji: '🏖' },
// ]
